line_length:
  - 200 # warning
  - 300 # error

file_length:
 - 500 # warning
 - 1500 # error

disabled_rules:
 - trailing_whitespace
 - identifier_name
 - force_cast
included: # paths to include during linting. `--path` is ignored if present.
  - TimeKeeping
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
