# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
# platform :ios, '8.0'

target 'Session2' do	
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'SideMenu'
	pod 'SwiftLint'
	pod 'RealmSwift'
    	pod 'Kingfisher', '~> 4.0'
	pod 'HAActionSheet'
    pod 'Alamofire', '~> 4.7'
    pod 'SwiftyJSON', '~> 3.1.4'

  # Pods for Session2

  target 'Session2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Session2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
